media_container_root_dir: "/media"

podqueue_opml_file_name: "podqueue.opml"

# Control which containers route through Wireguard or not
media_container_state:
  - name: bazarr
    network: container:wireguard
    ports:
      - "6767:6767"

  - name: jellyfin
    network: "bridge"
    ports:
      - "8096:8096/tcp"

  - name: overseerr
    network: "bridge"
    ports:
      - "5055:5055"

  - name: plex
    network: bridge
    ports:
      - "32400:32400/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"

  - name: podqueue
    network: "bridge"
    ports: []

  - name: prowlarr
    network: container:wireguard
    ports:
      - "9696:9696"

  - name: radarr
    network: container:wireguard
    ports:
      - "7878:7878"

  - name: sonarr
    network: container:wireguard
    ports:
      - "8989:8989"

  - name: tdarr
    network: "bridge"
    ports:
      - "8266:8266"
      - "8265:8265"

  - name: transmission
    network: container:wireguard
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"

  - name: youtubedl
    network: "bridge"
    ports: []

youtubedl_interval: "3h"
youtubedl_quality: "1080"

# Channel or Playlist URLs
youtubedl_content:
  - https://www.youtube.com/@programmersarealsohuman5909

# ----- ----- ----- ----- -----
# Wireguard Docker
# ----- ----- ----- ----- -----

wireguard_conf_file: "wireguard.conf.j2"
wireguard_tunnel_address: "10.2.0.2/32"
wireguard_endpoint_ip: "103.214.20.98"
wireguard_endpoint_port: "51820"
wireguard_public_key: "cyTFQG65skA/WgLJyt+WCvj2Y2i0wB+snKe0gWGd+Xo="
