- name: Create Minecraft container directory
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '755'
  loop:
    - "{{ docker_container_dir }}/minecraft_server"

- name: Install and start Minecraft through Docker
  community.docker.docker_container:
    name: minecraft_server
    image: "ghcr.io/itzg/minecraft-server"
    state: started
    pull: true
    cleanup: false
    detach: true
    init: true
    restart_policy: unless-stopped
    ports:
      - "{{ minecraft_port }}:{{ minecraft_port }}"
    env:
      TZ: "{{ time_zone }}"
      EULA: "TRUE"
      TYPE: "FABRIC"
      VERSION: "{{ minecraft_version }}"
      MEMORY: "{{ minecraft_ram_mb }}m"
      MAX_MEMORY: "{{ minecraft_ram_mb }}m"
      OPS: "{{ minecraft_ops | join(',') }}"
      ENABLE_WHITELIST: "{{ minecraft_use_allowlist | string }}"
      WHITELIST: "{{ minecraft_allowlist | join(',') }}"
      RCON_PASSWORD: "{{ mcrcon_pass }}"
      MODRINTH_PROJECTS: "{{ minecraft_mods | join(',') }}"
      LEVEL: "{{ minecraft_world_name }}"
      SPAWN_PROTECTION: "0"
      SEED: "{{ minecraft_seed }}"
      DIFFICULTY: "{{ minecraft_difficulty }}"
      MOTD: "{{ minecraft_motd }}"
      SIMULATION_DISTANCE: "10"
      VIEW_DISTANCE: "12"
      SERVER_PORT: "{{ minecraft_port | string }}"
    volumes:
      - "{{ docker_container_dir }}/minecraft_server:/data"
