- name: Core playbook
  hosts: "*"
  become: yes

  environment:
    PATH: "{{ ansible_env.PATH }}:/home/{{ username }}/.cargo/bin"

  # ----- ----- ----- ----- -----
  # Task imports
  # ----- ----- ----- ----- -----

  tasks:

    # ----- ----- ----- ----- -----
    # CORE
    # ----- ----- ----- ----- -----

    - include_role:
        name: core
      vars:
        node_exporter_hash: "{{ secret_node_exporter_hash }}"


    - include_role:
        name: fs_snapshots

    # ----- ----- ----- ----- -----
    # WORKSTATION
    # ----- ----- ----- ----- -----

    - when: inventory_hostname in groups.workstation
      block:
        - include_role:
            name: workstation

        - include_role:
            name: vscode

        - include_role:
            name: gdrive_obsidian
          vars:
            gdrive_client_id: "{{ secret_gdrive_client_id }}"
            gdrive_client_secret: "{{ secret_gdrive_client_secret }}"
            gdrive_root_folder_id: "{{ secret_gdrive_root_folder_id }}"

    # ----- ----- ----- ----- -----
    # SERVER
    # ----- ----- ----- ----- -----

    - when: inventory_hostname in groups.server
      block:
        - include_role:
            name: server

        # https://github.com/robertdebock/ansible-role-fail2ban
        - include_role:
            name: robertdebock.fail2ban

        # ----- ----- ----- ----- -----
        # MEDIA
        # ----- ----- ----- ----- -----

        - include_role:
            name: media
          when: inventory_hostname in groups.media

        # ----- ----- ----- ----- -----
        # MINECRAFT
        # ----- ----- ----- ----- -----

        - name: Minecraft role
          include_role:
            name: tquin.minecraft_fabric_server
          when: inventory_hostname in groups.minecraft
          vars:
            mcrcon_pass: "{{ secret_mcrcon_pass }}"
            minecraft_ops: "{{ secret_minecraft_ops }}"
            minecraft_allowlist: "{{ secret_minecraft_allowlist }}"

        # ----- ----- ----- ----- -----
        # BACKUP
        # ----- ----- ----- ----- -----

        - name: Backup role
          include_role:
            name: rclone_backup
          when: inventory_hostname in groups.backup
          vars:
            # HTTP server
            rclone_rc_pass: "{{ secret_rclone_rc_pass }}"
            # Google Photos
            rclone_gphotos_token: "{{ secret_rclone_gphotos_token | string }}"
            # Backblaze B2
            rclone_b2_account: "{{ secret_rclone_b2_account }}"
            rclone_b2_key: "{{ secret_rclone_b2_key }}"
            rclone_b2_crypt_pass: "{{ secret_rclone_b2_crypt_pass }}"

        # ----- ----- ----- ----- -----
        # MONITORING
        # ----- ----- ----- ----- -----

        - include_role:
            name: monitoring
          when: inventory_hostname in groups.monitoring
          vars:
            node_exporter_pass: "{{ secret_node_exporter_pass }}"

        # ----- ----- ----- ----- -----
        # PUBLIC HOSTING
        # ----- ----- ----- ----- -----

        - include_role:
            name: public_hosting
          when: inventory_hostname in groups.public_hosting
          vars:
            cf_dns_token: "{{ secret_cf_dns_token }}"
            caddy_email: "{{ secret_cloudflare_email }}"
