# ----- ----- ----- ----- -----
# Flatpak & Appimages
# ----- ----- ----- ----- -----

flatpak_packages:
  - io.github.shiftey.Desktop # Github Desktop
  - md.obsidian.Obsidian
  - org.signal.Signal
  - com.spotify.Client
  - org.gnome.baobab # Disk Usage Analyzer
  - org.gimp.GIMP
  - com.discordapp.Discord
  - com.valvesoftware.Steam
  - org.gnome.Extensions
  - com.github.tchx84.Flatseal # Flatpak permission manager
  - im.riot.Riot # Element Matrix client
  - io.gitlab.adhami3310.Impression # ISO writer
  - com.github.d4nj1.tlpui # TLP frontend for power usage
  - org.gnome.World.PikaBackup # Borg frontend
  - io.missioncenter.MissionCenter
  - dev.zed.Zed
  - com.vscodium.codium

appimage_install_dir: "/home/{{ username }}/.local/bin"
appimage_icon_dir: "/usr/share/pixmaps"

appimage_applications:
  - name: "GitButler"
    requires_decompressing: true
    app_url: "https://app.gitbutler.com/downloads/release/linux/x86_64/gz"
    icon_url: "https://raw.githubusercontent.com/gitbutlerapp/gitbutler/master/crates/gitbutler-tauri/icons/icon.png"

# ----- ----- ----- ----- -----
# GNOME
# ----- ----- ----- ----- -----

# Expected to be in roles/workstation/files/
gnome_wallpaper: "slow_rush_wallpaper.jpg"

firefox_pinned_app: >-
  {% if ansible_os_family == 'RedHat' %}
  firefox.desktop
  {% elif ansible_os_family == 'Debian' %}
  firefox_firefox.desktop
  {% endif %}

# Note this is in left -> right order on the dock
gnome_pinned_apps:
  - "{{ firefox_pinned_app | regex_replace('\\s', '') }}"
  - org.gnome.Nautilus.desktop
  - Alacritty.desktop
  - code.desktop # VS Code
  - md.obsidian.Obsidian.desktop

gnome_extensions:
  # - id: 6 # https://extensions.gnome.org/extension/6/applications-menu/
  - id: 7 # https://extensions.gnome.org/extension/7/removable-drive-menu/
  - id: 8 # https://extensions.gnome.org/extension/8/places-status-indicator/
  - id: 307 # https://extensions.gnome.org/extension/307/dash-to-dock/
  - id: 517 # https://extensions.gnome.org/extension/517/caffeine/
  - id: 1460 # https://extensions.gnome.org/extension/1460/vitals/
  - id: 6242 # https://extensions.gnome.org/extension/6242/emoji-copy/
  - id: 3733 # https://extensions.gnome.org/extension/3733/tiling-assistant/
  - id: 6631 # https://extensions.gnome.org/extension/6631/proton-vpn-button/
  - id: 6048 # https://extensions.gnome.org/extension/6048/peek-top-bar-on-fullscreen/
  - id: 1007 # https://extensions.gnome.org/extension/1007/window-is-ready-notification-remover/

gnome_systemd_manager_value: >-
  ['{"name":"Obsidian","service":"gdrive-obsidian.service","type":"system"}',
  '{"name":"Docker","service":"docker.service","type":"system"}',
  '{"name":"Tailscale","service":"tailscaled.service","type":"system"}']

gnome_extension_settings:
  - { key: "dash-to-dock/dock-fixed", value: "0" }
  - { key: "dash-to-dock/apply-custom-theme", value: "1" }
  - { key: "dash-to-dock/multi-monitor", value: "true" }
  - { key: "tiling-assistant/window-gap", value: "4" }

gnome_preferences_settings:
  # Fractional scaling
  - key: "/org/gnome/mutter/experimental-features"
    value: "['scale-monitor-framebuffer']"

  # Window buttons (min/max/close)
  - key: "/org/gnome/desktop/wm/preferences/button-layout"
    value: "'appmenu:minimize,close'"

# ----- ----- ----- ----- -----
# Nerd Fonts
# ----- ----- ----- ----- -----

font_details:
  - { name: "FiraCode", path: "", ext: "ttf" }
  - { name: "FiraMono", path: "", ext: "otf" }
  - { name: "JetBrainsMono", path: "Ligatures/", ext: "ttf" }

font_types:
  - Regular
  - Bold
  - Medium

# ----- ----- ----- ----- -----
# Alacritty
# ----- ----- ----- ----- -----

alacritty_version: "v0.13.0"
