prod:
  vars:
    ansible_user: "{{ username }}"
    ansible_connection: ssh
    ansible_ssh_private_key_file: "/home/{{ username }}/.ssh/ansible"

  hosts:
    MANCHESTER-BABY:
      ansible_host: disabled # 100.68.26.36
    DEBOMBE:
      ansible_host: disabled # 100.105.52.65 

# ----- ----- ----- ----- -----

test:
  vars:
    ansible_user: "{{ username }}"
    ansible_connection: ssh
    ansible_ssh_private_key_file: "/home/{{ username }}/.ssh/ansible"

  hosts:
    ansiblevm-ubuntu2204:
      ansible_host: 192.168.124.232
    ansiblevm-debian12:
      ansible_host: 192.168.124.103
    ansiblevm-fedora40:
      ansible_host: 192.168.124.168
