# Use this file to choose which role-specific actions
# to apply to each host or group. EG: if you want
# minecraft server installed, add it to the [minecraft] group.

# You can put entire groups into the children: field,
# or individual hosts under hosts:

# Children groups can also show dependencies,
# such as [media] being dependent on the [server] role

workstation:
  hosts:
    MANCHESTER-BABY:
  children:

# ----- ----- ----- ----- -----

server:
  hosts:
    DEBOMBE:
  children:
    test:

    # ----- ----- ----- ----- -----

    media:
      hosts:
        DEBOMBE:
      children:
        test:

    # ----- ----- ----- ----- -----

    minecraft:
      hosts:
        DEBOMBE:
      children:
        test:

    # ----- ----- ----- ----- -----

    backup:
      hosts:
        DEBOMBE:
      children:
        test:

    # ----- ----- ----- ----- -----

    monitoring:
      hosts:
        DEBOMBE:
      children:
        test:

    # ----- ----- ----- ----- -----

    nextcloud:
      hosts:
        ansiblevm-fedora40:
      children:
      
    # ----- ----- ----- ----- -----

    public_hosting:
      hosts:
        DEBOMBE:
      children:
