- name: Add Apt signing key from official docker repo
  when: ansible_os_family == 'Debian'
  ansible.builtin.deb822_repository:
    name: docker
    types:
      - deb
    uris:
      - "https://download.docker.com/linux/{{ ansible_distribution | lower }}"
    state: present
    signed_by: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    architectures:
      - amd64
    suites:
      - "{{ ansible_distribution_release }}"
    components:
      - stable

- name: Update apt to load new repo
  ansible.builtin.apt:
    update_cache: yes

- name: Add Docker dnf repository
  when: ansible_os_family == 'RedHat'
  get_url:
    url: https://download.docker.com/linux/fedora/docker-ce.repo
    dest: /etc/yum.repos.d
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "660"

# ----- ----- ----- ----- -----

- name: Install Docker packages
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin

- name: Enable and start Docker service
  systemd:
    daemon_reload: true
    enabled: true
    state: started
    name: docker.service

# ----- ----- ----- ----- -----

- name: Add user to docker group for sudo-less commands
  user:
    name: "{{ username }}"
    groups: docker
    append: yes
