- name: Add Apt signing key from official docker repo
  when: ansible_os_family == 'Debian'
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present

- name: Add Docker apt repository
  when: ansible_os_family == 'Debian'
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present

- name: Add Docker dnf repository
  when: ansible_os_family == 'RedHat'
  get_url:
    url: https://download.docker.com/linux/fedora/docker-ce.repo
    dest: /etc/yum.repos.d
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "660"

# ----- ----- ----- ----- -----

- name: Install Docker packages
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin

- name: Enable and start Docker service
  systemd:
    daemon_reload: true
    enabled: true
    state: started
    name: docker.service

# ----- ----- ----- ----- -----

- name: Add user to docker group for sudo-less commands
  user:
    name: "{{ username }}"
    groups: docker
    append: yes
