# https://github.com/artis3n/ansible-role-tailscale
- name: Install tailscale
  include_role:
    name: artis3n.tailscale.machine
  vars:
    tailscale_authkey: "{{ secret_tailscale_authkey }}"
    tailscale_args: "--ssh"
    state: latest

- name: Add HTTPS certificate
  command: "tailscale cert {{ inventory_hostname | lower }}.{{ secret_tailscale_domain }}.ts.net"
