- name: Install and start cf-ddns through Docker
  community.docker.docker_container:
    name: cf-ddns
    image: favonia/cloudflare-ddns
    state: started
    pull: true
    cleanup: false
    detach: true
    restart_policy: unless-stopped
    user: "{{ username_uid }}:{{ username_guid }}"
    network_mode: host
    env:
      TZ: "{{ time_zone }}"
      PROXIED: "true"
      CF_API_TOKEN: "{{ cf_dns_token }}"
      DOMAINS: "{{ cf_ddns_domains | join(',') }}"
