##### ##### ##### ##### #####
# btrfs
##### ##### ##### ##### #####

snapper_templates:
  default:
    TIMELINE_LIMIT_HOURLY: 24
    TIMELINE_LIMIT_DAILY: 7
    TIMELINE_LIMIT_WEEKLY: 0
    TIMELINE_LIMIT_MONTHLY: 3
    TIMELINE_LIMIT_YEARLY: 0

##### ##### ##### ##### #####
# ZFS
##### ##### ##### ##### #####

# Default is 2AM on first Sunday of every month
zpool_scrub_schedule: "Sun *-*-1..7 02:00:00"

sanoid_templates:
  - name: default
    frequently: 0
    hourly: 24
    daily: 7
    monthly: 3
    yearly: 0
    autosnap: "yes"
    autoprune: "yes"

# Should snapping a dataset also snap all its children?
zfs_snap_recursive: no

# Ignore the Ubuntu Root-on-ZFS datasets, eg. /var and /usr
# This will still include 'rpool/USERDATA for /home'
# See: https://openzfs.github.io/openzfs-docs/Getting%20Started/Ubuntu/Ubuntu%2020.04%20Root%20on%20ZFS.html#step-3-system-installation
zfs_snap_denylist_patterns:
  - '^bpool'
  - '^rpool/ROOT'
  - '^rpool$'
