- name: Create Bazarr directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '755'
  loop:
    - "{{ docker_container_dir }}/bazarr/config"
    - "{{ media_container_root_dir }}"

- set_fact:
    bazarr_ports: "{{ (item.ports) if item.network != 'container:wireguard' else [] }}"
    bazarr_network: "{{ item.network }}"
  loop: "{{ media_container_state | community.general.json_query(_query) }}"
  vars:
    _query: "[?name=='bazarr']"

- name: Install and start Bazarr through Docker
  community.docker.docker_container:
    name: bazarr
    image: ghcr.io/hotio/bazarr
    state: started
    pull: true
    cleanup: false
    detach: true
    restart_policy: unless-stopped
    network_mode: "{{ bazarr_network }}"
    ports: "{{ bazarr_ports }}"
    env:
      TZ: "{{ time_zone }}"
      PUID: "{{ username_uid }}"
      PGID: "{{ username_guid }}"
    volumes:
      - "{{ docker_container_dir }}/bazarr/config:/config"
      - "{{ media_container_root_dir }}:/data"
