- name: Create Overseerr directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '755'
  loop:
    - "{{ docker_container_dir }}/overseerr/config"
    - "{{ media_container_root_dir }}"

- set_fact:
    overseerr_ports: "{{ (item.ports) if item.network != 'container:wireguard' else [] }}"
    overseerr_network: "{{ item.network }}"
  loop: "{{ media_container_state | community.general.json_query(_query) }}"
  vars:
    _query: "[?name=='overseerr']"

- name: Install and start Overseerr through Docker
  community.docker.docker_container:
    name: overseerr
    image: sctx/overseerr
    state: started
    pull: true
    cleanup: false
    detach: true
    restart_policy: unless-stopped
    network_mode: "{{ overseerr_network }}"
    ports: "{{ overseerr_ports }}"
    env:
      TZ: "{{ time_zone }}"
      PUID: "{{ username_uid }}"
      PGID: "{{ username_guid }}"
      PORT: "5055"
    volumes:
      - "{{ docker_container_dir }}/overseerr/config:/app/config"
      - "{{ docker_container_dir }}/common:/common"
