- name: Create podqueue directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '755'
  loop:
    - "{{ docker_container_dir }}/podqueue/config"
    - "{{ media_container_root_dir }}/podcasts"

- name: Copy podqueue.opml file
  become_user: "{{ username }}"
  copy:
    src: "{{ podqueue_opml_file_name }}"
    dest: "{{ docker_container_dir }}/podqueue/config/podqueue.opml"
    owner: "{{ username }}"
    group: "{{ username }}"
    # Note: this has to be a string, not an int!!
    mode: '660'

- set_fact:
    podqueue_ports: "{{ (item.ports) if item.network != 'container:wireguard' else [] }}"
    podqueue_network: "{{ item.network }}"
  loop: "{{ media_container_state | community.general.json_query(_query) }}"
  vars:
    _query: "[?name=='podqueue']"

- name: Install and start podqueue through Docker
  community.docker.docker_container:
    name: podqueue
    image: tquin/podqueue
    state: started
    user: "{{ username_uid }}:{{ username_guid }}"
    pull: true
    cleanup: false
    detach: true
    restart_policy: unless-stopped
    network_mode: "{{ podqueue_network }}"
    ports: "{{ podqueue_ports }}"
    env:
      TZ: "{{ time_zone }}"
      PUID: "{{ username_uid }}"
      PGID: "{{ username_guid }}"
      PQ_SERVER: "true"
    volumes:
      - "{{ media_container_root_dir }}/podcasts:/data"
      - "{{ docker_container_dir }}/podqueue/config:/config"
      - "{{ docker_container_dir }}/common:/common"
