- name: Create Prowlarr directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '755'
  loop:
    - "{{ docker_container_dir }}/prowlarr/config"

- set_fact:
    prowlarr_ports: "{{ (item.ports) if item.network != 'container:wireguard' else [] }}"
    prowlarr_network: "{{ item.network }}"
  loop: "{{ media_container_state | community.general.json_query(_query) }}"
  vars:
    _query: "[?name=='prowlarr']"

- name: Install and start Prowlarr through Docker
  community.docker.docker_container:
    name: prowlarr
    image: hotio/prowlarr
    state: started
    pull: true
    cleanup: false
    detach: true
    restart_policy: unless-stopped
    network_mode: "{{ prowlarr_network }}"
    ports: "{{ prowlarr_ports }}"
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 1
    env:
      TZ: "{{ time_zone }}"
      PUID: "{{ username_uid }}"
      PGID: "{{ username_guid }}"
    volumes:
      - "{{ docker_container_dir }}/prowlarr/config:/config"
      - "{{ docker_container_dir }}/common:/common"
