- name: Create Tdarr directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '755'
  loop:
    - "{{ docker_container_dir }}/tdarr/configs"
    - "{{ docker_container_dir }}/tdarr/server"
    - "{{ docker_container_dir }}/tdarr/logs"
    - "{{ docker_container_dir }}/tdarr/transcode_cache"
    - "{{ media_container_root_dir }}"

- set_fact:
    tdarr_ports: "{{ (item.ports) if item.network != 'container:wireguard' else [] }}"
    tdarr_network: "{{ item.network }}"
  loop: "{{ media_container_state | community.general.json_query(_query) }}"
  vars:
    _query: "[?name=='tdarr']"

- name: Install and start Tdarr through Docker
  community.docker.docker_container:
    name: tdarr
    image: ghcr.io/haveagitgat/tdarr
    state: started
    pull: true
    cleanup: false
    detach: true
    restart_policy: unless-stopped
    network_mode: "{{ tdarr_network }}"
    ports: "{{ tdarr_ports }}"
    env:
      TZ: "{{ time_zone }}"
      PUID: "{{ username_uid }}"
      PGID: "{{ username_guid }}"
      serverIP: "0.0.0.0"
      serverPort: "8266"
      webUIPort: "8265"
      internalNode: "true"
      inContainer: "true"
      nodeName: "MyInternalNode"
    volumes:
      - "{{ docker_container_dir }}/tdarr/configs:/app/configs"
      - "{{ docker_container_dir }}/tdarr/server:/app/server"
      - "{{ docker_container_dir }}/tdarr/logs:/app/logs"
      - "{{ docker_container_dir }}/tdarr/transcode_cache:/temp"
      - "{{ media_container_root_dir }}:/media"
