- name: Create youtubedl directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '755'
  loop:
    - "{{ docker_container_dir }}/youtubedl/config"
    - "{{ media_container_root_dir }}/youtubedl"

- name: Create channels.txt file
  file:
    path: "{{ docker_container_dir }}/youtubedl/config/channels.txt"
    state: touch
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'

- name: Add channels and playlists to youtubedl
  lineinfile:
    path: "{{ docker_container_dir }}/youtubedl/config/channels.txt"
    line: "{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'
  loop: "{{ youtubedl_content }}"

- set_fact:
    youtubedl_ports: "{{ (item.ports) if item.network != 'container:wireguard' else [] }}"
    youtubedl_network: "{{ item.network }}"
  loop: "{{ media_container_state | community.general.json_query(_query) }}"
  vars:
    _query: "[?name=='youtubedl']"

- name: Install and start youtubedl through Docker
  community.docker.docker_container:
    name: youtubedl
    image: jeeaaasustest/youtube-dl
    state: started
    # user: "{{ username_uid }}:{{ username_guid }}"
    pull: true
    cleanup: false
    detach: true
    restart_policy: unless-stopped
    network_mode: "{{ youtubedl_network }}"
    ports: "{{ youtubedl_ports }}"
    env:
      TZ: "{{ time_zone }}"
      PUID: "{{ username_uid }}"
      PGID: "{{ username_guid }}"
      youtubedl_interval: "{{ youtubedl_interval }}"
      youtubedl_quality: "{{ youtubedl_quality }}"
    volumes:
      - "{{ media_container_root_dir }}/youtubedl:/downloads"
      - "{{ docker_container_dir }}/youtubedl/config:/config"
